// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myweb.Data;

#nullable disable

namespace myweb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008133427_SeedCarsFeaturesBids")]
    partial class SeedCarsFeaturesBids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarFeature", b =>
                {
                    b.Property<int>("CarsId")
                        .HasColumnType("int");

                    b.Property<int>("FeaturesId")
                        .HasColumnType("int");

                    b.HasKey("CarsId", "FeaturesId");

                    b.HasIndex("FeaturesId");

                    b.ToTable("CarFeature");

                    b.HasData(
                        new
                        {
                            CarsId = 1,
                            FeaturesId = 1
                        },
                        new
                        {
                            CarsId = 1,
                            FeaturesId = 2
                        },
                        new
                        {
                            CarsId = 3,
                            FeaturesId = 1
                        },
                        new
                        {
                            CarsId = 3,
                            FeaturesId = 3
                        });
                });

            modelBuilder.Entity("myweb.Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("ClientId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 200m,
                            BidDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarId = 1,
                            ClientId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 220m,
                            BidDate = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarId = 1,
                            ClientId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 400m,
                            BidDate = new DateTime(2026, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CarId = 3,
                            ClientId = 3
                        });
                });

            modelBuilder.Entity("myweb.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Model = "Corolla",
                            PricePerDay = 180m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Kia",
                            Model = "Picanto",
                            PricePerDay = 120m,
                            Year = 2023
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Tesla",
                            Model = "Model 3",
                            PricePerDay = 350m,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("myweb.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "daniel.cohen@gmail.com",
                            FullName = "Daniel Cohen",
                            JoinDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "050-1234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "noa.levi@gmail.com",
                            FullName = "Noa Levi",
                            JoinDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "052-7654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "yossi.m@walla.co.il",
                            FullName = "Yossi Mizrahi",
                            JoinDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "054-1112233"
                        },
                        new
                        {
                            Id = 4,
                            Email = "maya.f@gmail.com",
                            FullName = "Maya Friedman",
                            JoinDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Email = "avi.peretz@hotmail.com",
                            FullName = "Avi Peretz",
                            JoinDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "053-9988776"
                        });
                });

            modelBuilder.Entity("myweb.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Navigation system",
                            Name = "GPS"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Air conditioning",
                            Name = "AC"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Phone connection",
                            Name = "Bluetooth"
                        });
                });

            modelBuilder.Entity("CarFeature", b =>
                {
                    b.HasOne("myweb.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("CarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myweb.Models.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("myweb.Models.Bid", b =>
                {
                    b.HasOne("myweb.Models.Car", "Car")
                        .WithMany("Bids")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myweb.Models.Client", "Client")
                        .WithMany("Bids")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("myweb.Models.Car", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("myweb.Models.Client", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
