// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myweb.Data;

#nullable disable

namespace myweb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008130541_SeedClients")]
    partial class SeedClients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("myweb.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "daniel.cohen@gmail.com",
                            FullName = "Daniel Cohen",
                            JoinDate = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "050-1234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "noa.levi@gmail.com",
                            FullName = "Noa Levi",
                            JoinDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "052-7654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "yossi.m@walla.co.il",
                            FullName = "Yossi Mizrahi",
                            JoinDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "054-1112233"
                        },
                        new
                        {
                            Id = 4,
                            Email = "maya.f@gmail.com",
                            FullName = "Maya Friedman",
                            JoinDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Email = "avi.peretz@hotmail.com",
                            FullName = "Avi Peretz",
                            JoinDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "053-9988776"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
